name: Deploy React App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env for Vite
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.ENV_VITE_EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.ENV_VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.ENV_VITE_EMAILJS_PUBLIC_KEY }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build Vite React app
        run: npm run build

      - name: Compress build files
        run: zip -r build.zip dist

      - name: Upload build.zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build.zip"
          target: "/var/www/"

      - name: Unzip on EC2 & Restart Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/
            rm -rf portfolio/*   # clear old build
            unzip -o build.zip
            mv dist/* portfolio/
            rm -rf dist build.zip
            sudo systemctl restart nginx
