name: Deploy React App to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env for Vite
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.ENV_VITE_EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.ENV_VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.ENV_VITE_EMAILJS_PUBLIC_KEY }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip build folder
        run: zip -r dist.zip dist

      - name: Upload dist.zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist.zip"
          target: "/var/www/portfolio/"

      - name: Unzip & Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/portfolio
            sudo rm -rf ./*              # remove old build safely
            sudo unzip dist.zip -d temp
            sudo mv temp/dist/* ./
            sudo rm -rf temp dist.zip
            sudo systemctl restart nginx
